opentelemetry-collector:
  config:
    exporters:
      otlp/honeycomb:
        endpoint: "api.honeycomb.io:443"
        headers:
          "x-honeycomb-team": "hcaik_01jhs58c09sj5t8sgy82ntqy84z4y18ejaq67esz37cz09jxb7rk1v4hq9"
          "x-honeycomb-dataset": "webstore-metrics"
    service:
      pipelines:
        traces:
          exporters:
            - otlp
            - debug
            - spanmetrics
            - otlp/honeycomb
        metrics:
          exporters:
            - otlphttp/prometheus
            - debug
            - otlp/honeycomb
        logs:
          exporters:
            - opensearch
            - debug
            - otlp/honeycomb